baseurl = "http://gosparta.io/"
languageCode = "en-us"
title = "Sparta"
theme = "hugo-material-docs"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-70794971-1"
# Code highlighting
# https://gohugo.io/content-management/syntax-highlighting
pygmentsStyle="tango"

[params]
	# General information
	author = "Matt Weagle"
	description = "Sparta - Go framework for AWS Lambda"
	copyright = "Copyright 2015-2017 Matt Weagle"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/mweagle/Sparta"

	version = "0.30.0"
	logo = "images/SpartaHelmet.png"
	favicon = "favicons/favicon.ico"

	permalink = "#"

	# Custom assets
	custom_css = ["css/sparta.css",
	"external/mermaid_dist/mermaid.css",
	"external/font-awesome-4.7.0/css/font-awesome.min.css"]
	custom_js  = ["external/mermaid_dist/mermaid.min.js",
	"external/jquery/jquery-2.2.0.min.js"]


[params.palette]
		primary = "grey"
		accent  = "indigo"

[params.font]
    text = "Open Sans"
    code = "Source Code Pro"

[social]
	twitter = "mweagle"
	github  = "mweagle"
	email   = "mweagle@gmail.com"

[[menu.main]]
	name   = "Sparta"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "Overview"
	url    = "/docs/overview"
	weight = 10

[[menu.main]]
	name   = "Sample Service"
	url    = "/docs/intro_example/intro"
	weight = 20

[[menu.main]]
	name   = "Documentation"
	weight = 30

# [[menu.main]]
# 	name   = "Roadmap"
# 	url    = "roadmap/"
# 	weight = 30

[[menu.main]]
	name   = "Presentations"
	url    = "/docs/presentations"
	weight = 900



[[menu.main]]
	name   = "Limitations"
	url    = "/docs/limitations"
	weight = 950


[[menu.main]]
	name   = "FAQ"
	url    = "/docs/faq"
	weight = 999


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

