
[[dependencies]]
  name = "github.com/Sirupsen/logrus"
  revision = "7f976d3a76720c4c27af2ba716b85d2e0a7e38b1"

[[dependencies]]
  name = "github.com/asaskevich/govalidator"
  revision = "4918b99a7cb949bb295f3c7bbaf24b577d806e35"

[[dependencies]]
  revision = "b709581f82a77c0ff00790d1446c05719fed714d"
  name = "github.com/aws/aws-sdk-go"

[[dependencies]]
  branch = "master"
  name = "github.com/mweagle/go-cloudformation"

[[dependencies]]
  branch = "master"
  name = "github.com/mweagle/cloudformationresources"

[[dependencies]]
  name = "github.com/spf13/cobra"
  revision = "c46add8a652801b61513ad36c56759f302fbb028"

[[dependencies]]
  branch = "master"
  name = "golang.org/x/tools"
