# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/AlecAivazis/survey"
  version = "1.6.2"

[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.6.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.26"

[[constraint]]
  name = "github.com/briandowns/spinner"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-broadcast"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"

[[constraint]]
  branch = "master"
  name = "github.com/fzipp/gocyclo"

[[constraint]]
  name = "github.com/gdamore/tcell"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/lint"

[[constraint]]
  branch = "master"
  name = "github.com/google/pprof"

[[constraint]]
  branch = "master"
  name = "github.com/hokaccha/go-prettyjson"

[[constraint]]
  name = "github.com/mjibson/esc"
  version = "0.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/mweagle/go-cloudcondenser"

[[constraint]]
  branch = "master"
  name = "github.com/mweagle/go-cloudformation"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/rivo/tview"

[[constraint]]
  name = "github.com/securego/gosec"
  version = "1.1.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/zcalusic/sysinfo"

[[constraint]]
  branch = "master"
  name = "golang.org/x/tools"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.21.0"

[[constraint]]
  name = "honnef.co/go/tools"
  version = "2017.2.2"

[prune]
  go-tests = true
  unused-packages = true
