# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/AlecAivazis/survey"
  version = "1.5.3"

[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.1.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.38"

[[constraint]]
  name = "github.com/briandowns/spinner"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"

[[constraint]]
  branch = "master"
  name = "github.com/google/pprof"

[[constraint]]
  branch = "master"
  name = "github.com/mweagle/go-cloudcondenser"

[[constraint]]
  branch = "master"
  name = "github.com/mweagle/go-cloudformation"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/zcalusic/sysinfo"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.15.0"

[prune]
  go-tests = true
  unused-packages = true
