name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      S3_BUCKET: weagle
      AWS_ACCESS_KEY_ID: ${{ AWS_ACCESS_KEY_ID }}
      AWS_REGION: ${{ AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get prerequities
        # Workaround for https://github.com/golang/go/issues/30515
        run: |
          ./prerequisites.sh

      - name: Build
        # Workaround for https://github.com/golang/go/issues/30515
        run: |
          go build .

      - name: CI build
        run: |
          mage -v travisBuild
